<?xml version="1.0" encoding="utf-8"?><Database Name="CustomerDB" Class="DataClassesDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="WebSettings" ConnectionString="Data Source=.\sqlexpress;Initial Catalog=CustomerDB;Integrated Security=True" SettingsObjectName="System.Configuration.ConfigurationManager.ConnectionStrings" SettingsPropertyName="CustomerDBConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.City" Member="Cities">
    <Type Name="City">
      <Column Name="ZIPcode" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="City" Member="City1" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Association Name="City_Customer" Member="Customers" ThisKey="ZIPcode" OtherKey="ZIPcode" Type="Customer" />
    </Type>
  </Table>
  <Table Name="dbo.Customer" Member="Customers">
    <Type Name="Customer">
      <Column Name="CustomerID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="FistName" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="LastName" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Address" Type="System.String" DbType="VarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="ZIPcode" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="PhoneNumber" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Email" Type="System.String" DbType="VarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="SubscriptionID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="DateJoined" Type="System.DateTime" DbType="Date NOT NULL" CanBeNull="false" />
      <Column Name="Payed" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="Active" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Association Name="City_Customer" Member="City" ThisKey="ZIPcode" OtherKey="ZIPcode" Type="City" IsForeignKey="true" />
      <Association Name="Subscription_Customer" Member="Subscription" ThisKey="SubscriptionID" OtherKey="SubscriptionID" Type="Subscription" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Subscription" Member="Subscriptions">
    <Type Name="Subscription">
      <Column Name="SubscriptionID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="SubscriptionName" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="SubscriptionPeriod" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Price" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="Subscription_Customer" Member="Customers" ThisKey="SubscriptionID" OtherKey="SubscriptionID" Type="Customer" />
    </Type>
  </Table>
  <Function Name="dbo.SearchCustomers" Method="SearchCustomers">
    <Parameter Name="FistName" Parameter="fistName" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="LastName" Parameter="lastName" Type="System.String" DbType="VarChar(50)" />
    <ElementType Name="SearchCustomersResult">
      <Column Name="CustomerID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="FistName" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="LastName" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Address" Type="System.String" DbType="VarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="ZIPcode" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="City" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="PhoneNumber" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Email" Type="System.String" DbType="VarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="SubscriptionName" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="SubscriptionPeriod" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="SubscriptionID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="DateJoined" Type="System.DateTime" DbType="Date NOT NULL" CanBeNull="false" />
      <Column Name="Active" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="Payed" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
    </ElementType>
  </Function>
</Database>